services:
  system-agent:
    image: yagatito/system-agent-${PLATFORM_ARCH}:1.0
    container_name: system-agent
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      DEVICE_AGENT: "${DEVICE_AGENT}"
      LOCATION_LAT: "${LOCATION_LAT}"
      LOCATION_LON: "${LOCATION_LON}"
      WEATHER_TOKEN: "${WEATHER_TOKEN}"
      WEATHER_PLUGIN: "${WEATHER_PLUGIN}"
    volumes:
      - /sys:/sys:ro
      - /proc:/proc:ro
      - /dev:/dev
