FROM --platform=$BUILDPLATFORM golang:1.26 AS builder
WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o /bin/agent-service ./cmd

FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /bin/agent-service .

CMD ["./agent-service"]